### ISSUE TITLE
Prepare for deprecation of jQueryObject and id selector as `container` option

### ISSUE THREAD

**Issue by heenakwag** [nhn/tui.pagination#18]
## TODO
* [x] Notice that passing the jQueryObject as the container will be deprecated in v4.0
* [x] Notice that considering as id selector when the container is a string will be deprecated in v4.0
* [x] Also use `querySelector` when the container is a string
* ref: https://github.com/nhn/tui.pagination/pull/16#discussion_r358533095
